index:
  subtitle:
    A multi-doc summarization dataset with summaries of three granularities
  description: | 
      Multi-LexSum is a multi-doc summarization dataset for civil rights litigations lawsuits with summaries of three granularities. 
  background:
    motivation: |
      Legal experts needs to read ***multiple long*** documents to understand a lawsuit. 
    docs: 
      - title: Docket
        icon: 'assets/example-docs/docket.svg'
        image: 'assets/example-docs/docket.jpg'
        description: The court's record of everything that has happened in a case
        link: https://clearinghouse.net/doc/23477/
      - title: Complaint
        icon: 'assets/example-docs/complaint.svg'
        image: 'assets/example-docs/complaint.jpg'
        description: The document that starts a case, establishing the parties and claims
        link: https://clearinghouse.net/doc/23481/
      - title: Motions/Briefs
        icon: 'assets/example-docs/motion.svg'
        image: 'assets/example-docs/motion.jpg'
        description: Documents filed by the parties in order to make their arguments
        link: https://clearinghouse.net/doc/1128/
      - title: Opinions
        icon: 'assets/example-docs/opinion.svg'
        image: 'assets/example-docs/opinion.jpg'
        description: Created by the judge(s) to memorialize rulings in the case
        link: https://clearinghouse.net/doc/33726/
      - title: Settlement
        icon: 'assets/example-docs/settlement.svg'
        image: 'assets/example-docs/settlement.jpg'
        description: An agreement among parties that resolves some issues in the case
        link: https://clearinghouse.net/doc/33727/
    summary: |
      Summaries of ***three different granularities*** are created to facilitate their understanding. 
    summaries: 
      - length: long 
        description: Multiple paragraphs, ~650 words
        text: |
          This case is about an apprenticeship test that had a disparate impact on Black apprenticeship applicants. The Equal Employment Opportunity Commission (EEOC) filed this lawsuit on December 27, 2004, in U.S. District Court for the Southern District of Ohio. Filing on behalf of thirteen Black individuals and a class of similarly situated Black apprenticeship test takers, the EEOC alleged that the individuals' employer, the Ford Motor Company, as well as their union, the United Automobile, Aerospace, and Agricultural implement workers of America (the "UAW"), and the Ford-UAW Joint Apprenticeship Committee, violated Title VII of the Civil Rights Act, 42 U.S.C. ยง 1981, and Michigan state anti-discrimination law. At issue were the selection tests for apprenticeship training programs, whose disparate impact denied Black applicants eligibility and admission. The EEOC sought injunctive relief, as well as damages (including backpay) for the Black apprenticeship applicants. The case was assigned to Judge Susan J. Dlott.


          The individuals also brought a separate class action against Ford and the UAW, Robinson v. Ford Motor Company, (No. 1:04-cv-00844), and the cases were consolidated on January 6, 2005. As a result, the case was transferred to Judge S. Arthur Spiegel. Six months later, in June 2005, both cases were resolved via a class settlement agreement. Ford agreed to pay $8.55 million and to implement a new selection process for its apprenticeship programs. This agreement further required Ford to hire an industrial psychologist to design this new selection process and to place 279 members of the settlement class on the eligibility list for the Ford apprenticeship program.


          On June 15, 2005, the court found that the proposed settlement agreement was fair. 2005 WL 5253339. The next day, the court ordered that Ford pay $1.1 million to cover attorneys' fees and expenses incurred during settlement negotiations, and $567,000 to cover fees and expenses associated with the implementation and monitoring of the settlement agreement. 2005 U.S. Dist. LEXIS 12071. As the settlement was initially scheduled to last for three years, and there is no further activity on the docket sheet, this case presumably closed in 2008.
      - length: short 
        description: Single paragraph, ~130 words
        text: |
          This case is about an apprenticeship test that had a disparate impact on Black apprenticeship applicants. The Equal Employment Opportunity Commission (EEOC) filed this lawsuit on December 27, 2004, in U.S. District Court for the Southern District of Ohio. Filing on behalf of thirteen Black individuals and a class of similarly situated Black apprenticeship test takers, the EEOC alleged that the individuals' employer, the Ford Motor Company, as well as their union, the United Automobile, Aerospace, and Agricultural implement workers of America (the "UAW"), and the Ford-UAW Joint Apprenticeship Committee, violated Title VII of the Civil Rights Act, 42 U.S.C. ยง 1981, and Michigan state anti-discrimination law. The EEOC sought injunctive relief and damages for the Black apprenticeship applicants. The individuals also brought a separate class action against Ford and the UAW, and the cases were consolidated. In June 2005, both cases were resolved via a class settlement agreement. Ford agreed to pay $8.55 million and to implement a new selection process for its apprenticeship programs, and the court ordered Ford to cover attorneys' fees and expenses. This case is closed.
      - length: tiny
        description: One sentence, ~25 words
        text: |
          2005 class action settlement resulted in Ford paying $8.55m to redesign its selection process for apprenticeship programs to address the previous process's disparate impact on Black applicants.
    dataset: |
      The Multi-LexSum dataset is a collection of 9,280 such legal case summaries.
      Multi-LexSum is distinct from other datasets in its **<span class="is-underlined">multiple target summaries, each at a different granularity</span>** (ranging from one-sentence "extreme" summaries to multi-paragraph narrations of over five hundred words). 
      It presents a challenging multi-document summarization task given **<span class="is-underlined">the long length of the source documents</span>**, often exceeding two hundred pages per case.
      
      Unlike other summarization datasets that are (semi-)automatically curated, Multi-LexSum consists of **<span class="is-underlined">expert-authored summaries</span>**: the experts---lawyers and law students---are trained to follow carefully created guidelines, and their work is reviewed by an additional expert to ensure quality. 
      
      <div style="max-width: 50%">
        <img src="/assets/summary-writing.png"
            alt="The summary writing process in Multi-LexSum">
      </div>

      For more details on how the dataset is created, please refer to the [dataset sheet](https://docs.google.com/document/d/1bkPQeoiwjh8CVL5usJD77W2qBXmRFu1-BJUDXb1Vm6U/edit?usp=sharing) and [our paper](https://arxiv.org/abs/2206.10883). 

    license: |
      The Multi-LexSum dataset is distributed under the [Open Data Commons Attribution License (ODC-By)](https://opendatacommons.org/licenses/by/1-0/). 
      The case summaries and metadata are licensed under the [Creative Commons Attribution License (CC BY-NC)](https://creativecommons.org/licenses/by-nc/4.0/), and the source documents are already in the public domain. 
      Commercial users who desire a license for summaries and metadata can contact [info@clearinghouse.net](mailto:info@clearinghouse.net), which will allow free use but limit summary re-posting. 
      The corresponding code for downloading and loading the dataset is licensed under the Apache License 2.0. 

    download: |
      The Multi-LexSum dataset can be loaded via HuggingFace Datasets:

    downloadcode: |

      ```python
      from datasets import load_dataset
      
      multi_lexsum = load_dataset("multi_lexsum.py", name="v20220616")
      # Download multi_lexsum locally and load it as a Dataset object 
      
      example = multi_lexsum["validation"][0] # The first instance of the dev set 
      example["sources"] # A list of source document text for the case
      
      for sum_len in ["long", "short", "tiny"]:
          print(example["summary/" + sum_len]) # Summaries of three lengths
      ```
    
    download2: | 
      Right now we are working on merging the script to the official HF dataset library. Therefore 
      you might need to download the `multi_lexsum.py` file manually from our [Github repo](https://github.com/multilexsum/dataset).

    teamoverview: |
      The Multi-LexSum dataset are created by the joint effort between the [Allen Institute for Artificial Intelligence](https://allenai.org/) and [Civil Rights Litigation Clearinghouse](https://clearinghouse.net/) from the [University of Michigan](https://umich.edu/). The team members are: 
    
    teamoverview2: |
      Also hundreds of law student authored of the case summaries in Multi-LexSum, and their names are listed [here](https://clearinghouse.net/people).
      
footnote: 